### ISSUE TITLE
Fails to START THE APP

### ISSUE THREAD

**Issue by alexcoffee** [swarm-pack/swarm-sync#13]
docker run -it  -v /var/run/docker.sock:/var/run/docker.sock  -v swarm-sync.yml:/etc/swarm-sync.yml  kevbuk/swarm-sync --once

LOADING SECRETS...
Pulling environment secrets...
Finised pulling environment secrets
START THE APP...
(node:20) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/cjs/loader.js:794
      internalBinding('util').triggerFatalException(e);
                              ^

Error: Cannot find module /www/src/index.mjs
    at search (internal/modules/esm/default_resolve.js:29:12)
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:65:11)
    at Loader.resolve (internal/modules/esm/loader.js:58:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:113:40)
    at Loader.import (internal/modules/esm/loader.js:99:28)
    at asyncESM.loaderPromise.then (internal/modules/cjs/loader.js:791:27)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:800:11)
    at executeUserCode (internal/bootstrap/node.js:526:15)

**Comment by juanise** [comment]
The same thing happened to me:

docker run -it \                                                                                                                                                                           
>  -v /var/run/docker.sock:/var/run/docker.sock \
>  -v /path/to/swarm-sync.yml:/etc/swarm-sync.yml \
>  kevbuk/swarm-sync --bootstrap
LOADING SECRETS...
Pulling environment secrets...
Finised pulling environment secrets
START THE APP...
(node:20) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/cjs/loader.js:794
      internalBinding('util').triggerFatalException(e);
                              ^

Error: Cannot find module /www/src/index.mjs
    at search (internal/modules/esm/default_resolve.js:29:12)
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:65:11)
    at Loader.resolve (internal/modules/esm/loader.js:58:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:113:40)
    at Loader.import (internal/modules/esm/loader.js:99:28)
    at asyncESM.loaderPromise.then (internal/modules/cjs/loader.js:791:27)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:800:11)
    at executeUserCode (internal/bootstrap/node.js:526:15)

**Comment by github-anis-snoussi** [comment]
same error here, I'm using the example in the README
